name: httomo
channels:
  - conda-forge
  - anaconda
  - httomo
dependencies:
  - conda-forge::click>=8.1.3
  - conda-forge::h5py=*=*mpi_openmpi*
  - conda-forge::loguru
  - conda-forge::mpi4py>=3.1
  - conda-forge::numexpr>=2.8.4
  - conda-forge::numpy<1.24
  - conda-forge::pyyaml
  - conda-forge::python
  - conda-forge::tomopy==1.15
  - conda-forge::tqdm
  - conda-forge::typing_extensions
  - anaconda::ipython
  - httomo::httomolib==2.0
