name: httomo
channels:
  - conda-forge
dependencies:
  - scipy
  - pillow
  - click
  - numpy
  - graypy
  - h5py=*=*mpi_openmpi*
  - hdf5plugin
  - loguru
  - mpi4py
  - pyyaml
  - nvtx
  - python
  - plumbum
  - tqdm
  - typing_extensions
  - ipython
  - pytest
  - pytest-xdist
  - pytest-cov
  - pytest-mock
