name: httomo
channels:
  - conda-forge
  - anaconda
  - httomo
dependencies:
  - conda-forge::tomopy==1.15
  - httomo::httomolib==2.0
  - conda-forge::click>=8.1.3
  - conda-forge::mpi4py>=3.1
  - conda-forge::h5py=*=*mpi_openmpi*
  - conda-forge::pyyaml
  - conda-forge::numpy<=1.25
  - conda-forge::python 
  - conda-forge::numexpr>=2.8.4
  - anaconda::ipython
  - anaconda::loguru  
  - conda-forge::graypy
  - conda-forge::plumbum
  - conda-forge::tqdm
  - conda-forge::typing_extensions
