package:
  name: httomo
  version: "0.1"

source:
  path: ..

requirements:
  build:
    - python

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install

about:
  home: https://github.com/dkazanc/HTTO
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High Throughput Tomography framework'
