{% set pyproject = load_file_data("../../pyproject.toml", from_recipe_dir=True) %}
{% set proj = pyproject.get("project") %}
{% set name = proj.get("name") %}
{% set version = proj.get("version") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../

build:
  preserve_egg_dir: False
  number: 0

test:
  files:
    - samples/*
    - yaml_templates/*
  requires:
    - pip
    - pytest
  imports:
    - httomo
    - httomo.data
  source_files:
    - tests/*
  commands:
    - pip check
    - pytest 
requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy>= 1.20, <= 1.25
    - cupy>=12.3
    - mpi4py>=3.1
    - h5py>=3.8=mpi*
    - httomolib
    - tomopy
    - pyyaml
    - nvtx
    - click
    - setuptools
    - pytest

about:
  home: https://github.com/DiamondLightSource/httomo
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High Throughput Tomography framework'
