{% set pyproject = load_file_data("../../pyproject.toml", from_recipe_dir=True) %}
{% set proj = pyproject.get("project") %}
{% set name = proj.get("name") %}

package:
  name: {{ name|lower }}
  version: {{ GIT_DESCRIBE_TAG|trim("v") }}

source:
  path: ../../

build:
  preserve_egg_dir: False
  string: py{{ py }}_openmpi_{{ openmpi_build }}

test:
  files:
    - samples/*
    - yaml_templates/*
  requires:
    - pip
    - pytest
  imports:
    - httomo
    - httomo.data
  source_files:
    - tests/*
  commands:
    - pip check
    - pytest
requirements:
  build:
    - h5py=*=*mpi_openmpi*
    - httomolib==2.1
    - httomolibgpu==2.1
    - loguru
    - mpi4py
    - numpy<=1.25
    - pip
    - python
    - pyyaml
    - setuptools
    - setuptools-git-versioning
    - tomopy==1.15
    - typing_extensions
  run:
    - astra-toolbox
    - click>=8.1.3
    - cucim
    - cupy<=12.3.0
    - cudatoolkit
    - graypy
    - h5py=*=*mpi_openmpi*
    - hdf5plugin
    - httomolib==2.0
    - httomolibgpu==2.0
    - ipython
    - loguru
    - mpi4py
    - pyyaml
    - numpy<=1.25
    - nvtx
    {% if openmpi_build == 'regular' %}
    - openmpi
    {% else %}
    - openmpi * *external*
    {% endif %}
    - python
    - plumbum
    - tomobar
    - tomopy==1.15
    - tqdm
    - typing_extensions

about:
  home: https://github.com/DiamondLightSource/httomo
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High Throughput Tomography framework'
