name: conda test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - documentation
  push:
    branches:
      - main
      - documentation
jobs:
  httomo:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository code
          uses: actions/checkout@v3

        - name: Setup Python 3.9
          uses: actions/setup-python@v3
          with:
            python-version: 3.9

        - name: httomo
          uses: conda-incubator/setup-miniconda@v2
          with:
            auto-update-conda: false
            activate-environment: httomo
            environment-file: ./conda/explicit/latest.txt
            mamba-version: "*"
            channels: conda-forge
            channel-priority: true