name: conda test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  conda:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2

        - name: Setup Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Installing httomo
          uses: conda-incubator/setup-miniconda@v2
          with:
            auto-update-conda: false
            activate-environment: httomo
            environment-file: conda/explicit/latest.txt