name: httomo CPU tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      # setup Python 3.9
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # set up conda incubator that uses mamba
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge,httomo,astra-toolbox,anaconda
          channel-priority: false
          activate-environment: httomo
          environment-file: conda/environment.yml
