name: httomo CPU tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      # setup Python 3.9
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # install dependencies with mamba
      - name: Install dependencies with mamba
        run: |
          conda install -c conda-forge mamba
          mamba env create --name httomo --file conda/environment.yml
          mamba activate httomo
          mamba run -n httomo pip install -e .
          mamba run -n httomo pip install httomolib
          mamba env list
          mamba list

      # run tests
      - name: Run CPU tests (No CUDA drivers needed)
        run: |
          mamba run -n httomo pip install pytest
          mamba run -n httomo pytest -m "not cupy"
