name: HTTomo dev build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  
jobs:

  install-run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

        # setup Python 3.10
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda/environment.yml
          environment-name: httomo
          post-cleanup: 'all'
          init-shell: bash

      - name: Install httomo-dev from conda-cloud
        run: |
          micromamba activate httomo
          micromamba install "httomo/label/dev/linux-64::httomo * py310_openmpi_regular*" -c httomo -c conda-forge -c astra-toolbox -c rapidsai
          micromamba list

      - name: Run tests
        run: |
          pytest tests/


          