name: HTTomo doc conda env test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - documentation
  push:
    branches:
      - main
      - documentation
jobs:
  # Test for reusing a workflow
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: jessicavers/HTTomo/.github/workflows/yaml_generator.yml@documentation

      - name: Make conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: docs/source/doc-conda-requirements.yml

      - name: Build html
        run: docs/sphinx-build.sh

      - name: Run ghp-import
        run: ghp-import -n -p -f docs/build