name: HTTomo doc conda env test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  # Test for reusing a workflow
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: yaml_generator.yml@documentation

      - name: Make conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: doc/source/doc-conda-requirements.yml

      - name: Build html
        run: doc/sphinx-build.sh

      - name: Run ghp-import
        run: ghp-import -n -p -f doc/build