name: version tag pushed

# Run the workflow whenever a tag beginning with `v` is pushed to any branch
on:
  push:
    tags:
      - v*

jobs:
  conda-build-upload:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      # setup Python 3.11
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # setup conda
      - name: Setup conda
        uses: mamba-org/setup-micromamba@v2
        with:
          post-cleanup: 'all'
          init-shell: bash

      # install dependencies
      - name: Install dependencies
        run: |
          micromamba install -c conda-forge conda-build anaconda-client
          micromamba list

      - name: Decrypt a secret
        run: ./.scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Build and upload the package to httomo conda cloud
        env:
          LABEL: main
        run: |
          chmod +x ./.scripts/conda_upload.sh
          ./.scripts/conda_upload.sh
