name: version tag pushed

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# Run the workflow whenever a tag beginning with `v` is pushed to any branch
# on:
#   push:
#     tags:
#       - v*

jobs:
  conda-build-upload:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
        #   ref: ${{ github.ref_name }}

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda/environment.yml
          environment-name: httomo
          post-cleanup: 'all'
          init-shell: bash         
          condarc: |
            channels:
              - conda-forge
              - httomo

      # # setup Python 3.10
      # - name: Setup Python 3.10
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.10'

      # install dependencies with conda
      - name: Install dependencies with conda
        run: |
          micromamba activate httomo
          pip install .
          pip install httomolibgpu tomobar 
          mamba install -c conda-forge conda-build
          mamba install -c conda-forge anaconda-client
          micromamba list

      - name: Decrypt a secret
        run: ./.scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Build and upload the package to httomo conda cloud
        env:
          LABEL: main
        run: |
          chmod +x ./.scripts/conda_upload.sh
          ./.scripts/conda_upload.sh
