name: version tag pushed

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# Run the workflow whenever a tag beginning with `v` is pushed to any branch
# on:
#   push:
#     tags:
#       - v*

jobs:
  conda-build-upload:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
        #   ref: ${{ github.ref_name }}

      # setup Python 3.10
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # install dependencies with conda
      - name: Install dependencies with conda
        run: |
          $CONDA/bin/conda install -c conda-forge conda-build
          $CONDA/bin/conda install -c conda-forge anaconda-client
          $CONDA/bin/conda list

      - name: Decrypt a secret
        run: ./.scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Build and upload the package to httomo conda cloud
        env:
          LABEL: main
        run: |
          chmod +x ./.scripts/conda_upload.sh
          ./.scripts/conda_upload.sh
