name: Python linters

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # setup Python 3.10
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install black

      - name: Run Black linter
        uses: wearerequired/lint-action@v2
        with:
          black: true
