name: httomo nightly dev conda package build + upload

on:
  schedule:
    # Run at midnight every day
    - cron: '0 0 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          ref: "main"
          fetch-depth: 0

      # setup Python 3.9
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies with Conda
        run: |
          $CONDA/bin/conda install -c conda-forge conda-build
          $CONDA/bin/conda install -c conda-forge anaconda-client
          $CONDA/bin/conda update conda
          $CONDA/bin/conda update conda-build
          $CONDA/bin/conda list

      - name: Decrypt a secret
        run: ./.scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Build and upload the package to httomo conda cloud
        env:
          LABEL: dev
        run: |
          chmod +x ./.scripts/conda_upload.sh
          ./.scripts/conda_upload.sh

