name: HTTomo pipelines tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  iris-gpu:
    runs-on: iris-gpu
    container:
      image: nvidia/cuda:12.6.3-devel-ubi8
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda/environment.yml
          environment-name: httomo
          post-cleanup: 'all'
          init-shell: bash
          
      - name: Install httomo libraries, httomo-backends and httomo
        run: |
          micromamba activate httomo
          pip install --upgrade --force-reinstall pillow
          pip install httomolibgpu tomobar
          pip install --no-deps httomo-backends
          pip install .   
          micromamba list
                
      - name: Generate full yaml pipelines using pipeline directives
        run: |
          pip install "ruamel.yaml>0.18.0"
          python ./docs/source/scripts/yaml_pipelines_generator.py -i ./docs/source/pipelines_full/gpu_pipeline1_directive.yaml -o ./docs/source/pipelines_full/gpu_pipeline1.yaml
          python ./docs/source/scripts/yaml_pipelines_generator.py -i ./docs/source/pipelines_full/cpu_pipeline1_directive.yaml -o ./docs/source/pipelines_full/cpu_pipeline1.yaml

      - name: Run HTTomo pipelines tests (small data)
        run: |
          pytest tests/test_pipeline_small.py --pipeline_small
