name: HTTomo tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: httomo
          create-args: >-
            python==3.12
            numpy==2.4
            h5py=*=*mpi_openmpi*
            mpi4py
            tomopy==1.15.3
          post-cleanup: 'all'
          init-shell: bash

      - name: Install httomo libraries and httomo
        run: |
          micromamba activate httomo
          python -m pip install --no-deps pytest pytest-cov
          python -m pip install --no-deps tomobar
          python -m pip install --no-deps httomolibgpu
          python -m pip install --no-deps httomolib
          python -m pip install --no-deps httomo-backends          
          pip install . --no-deps
          micromamba list

      - name: Generate full yaml pipelines using pipeline directives
        run: |
          python -m pip install pyyaml pluggy Pygments iniconfig loguru tqdm graypy hdf5plugin pytest_mock plumbum click
          python -m pip install aiofiles pillow
          python -m pip install "ruamel.yaml>0.18.0"
          python ./docs/source/scripts/execute_pipelines_build.py -o ./docs/source/pipelines_full/

      - name: Run HTTomo framework tests
        run: |
          pytest tests/