name: HTTomo doc test

on:
  workflow_dispatch:
  workflow_call:
  push: -- Register wf

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
        - name: Checkout repository code
          uses: actions/checkout@v2

        - name: Setup Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Generate yml
          run: python templates/tomopy/yaml_generator_tomopy.py
